os: linux
dist: trusty

language: php

php:
  - '7.2'
  - '7.3'

before_install: skip

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - chmod +x php-coveralls.phar

script:
  - phpunit

after_success:
  - travis_retry php php-coveralls.phar